//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSD_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public class PieceVenteModel
    {
        public int ID { get; set; }
        public string NumPieceVente { get; set; }
        public Nullable<int> CodeClient { get; set; }    
    }
}
