//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSD_DAL.TSD_EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompteBancaire
    {
        public int ID { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> Owner { get; set; }
        public string TypeOwner { get; set; }
        public string RIB { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> BanqueId { get; set; }
    }
}
