//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSD_DAL.TSD_EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordonnees
    {
        public int ID { get; set; }
        public string Nom { get; set; }
        public string Adresse { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string MatriculeFiscale { get; set; }
        public string TelFixe { get; set; }
        public string Description { get; set; }
        public string URLimg { get; set; }
        public string Email { get; set; }
        public string RC { get; set; }
        public string RIB { get; set; }
    }
}
