//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSD_DAL.TSD_EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fournisseur
    {
        public int ID { get; set; }
        public string OwnerName { get; set; }
        public string Adresse { get; set; }
        public string CodePostal { get; set; }
        public string IBAN { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Fax { get; set; }
        public string MatriculeFiscal { get; set; }
        public bool IsActive { get; set; }
        public string FType { get; set; }
        public string Interlocuteur { get; set; }
        public string NumeroInterlocuteur { get; set; }
    }
}
