//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSD_DAL.TSD_EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnes
    {
        public int ID { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<int> Fonction { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public Nullable<int> SoldeCongeAnnuel { get; set; }
        public Nullable<double> SoldeCongeRestant { get; set; }
        public string AdresseEmail { get; set; }
        public Nullable<bool> IsActif { get; set; }
        public Nullable<System.DateTime> DateDebutContrat { get; set; }
        public Nullable<System.DateTime> DateFinContrat { get; set; }
        public Nullable<int> TypePaymentID { get; set; }
    }
}
