//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSD_DAL.TSD_EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Piece
    {
        public int ID { get; set; }
        public string NumPiece { get; set; }
        public string TypePiece { get; set; }
        public string Libelle { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string Statut { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public double MontantTotal { get; set; }
        public double MontantFinal { get; set; }
        public bool Closed { get; set; }
        public bool Comptabilise { get; set; }
        public double RAS { get; set; }
        public bool RASClosed { get; set; }
        public string Reference { get; set; }
    }
}
