//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSD_DAL.TSD_EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeriesTable
    {
        public int ID { get; set; }
        public Nullable<int> FCCounter { get; set; }
        public Nullable<int> FFCounter { get; set; }
        public Nullable<int> BLCounter { get; set; }
        public Nullable<int> BCCounter { get; set; }
    }
}
