//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSD_DAL.TSD_EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TSD_Gestion_CommercialeEntities : DbContext
    {
        public TSD_Gestion_CommercialeEntities()
            : base("name=TSD_Gestion_CommercialeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banque> Banque { get; set; }
        public virtual DbSet<CompteBancaire> CompteBancaire { get; set; }
        public virtual DbSet<Conges> Conges { get; set; }
        public virtual DbSet<Coordonnees> Coordonnees { get; set; }
        public virtual DbSet<Fonctions> Fonctions { get; set; }
        public virtual DbSet<Fournisseur> Fournisseur { get; set; }
        public virtual DbSet<JoursFeries> JoursFeries { get; set; }
        public virtual DbSet<MappingReglementPieces> MappingReglementPieces { get; set; }
        public virtual DbSet<MotifConge> MotifConge { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<NotificationsType> NotificationsType { get; set; }
        public virtual DbSet<Parameters> Parameters { get; set; }
        public virtual DbSet<PassagesClients> PassagesClients { get; set; }
        public virtual DbSet<Personnes> Personnes { get; set; }
        public virtual DbSet<PieceAchat> PieceAchat { get; set; }
        public virtual DbSet<PieceVente> PieceVente { get; set; }
        public virtual DbSet<Pricing> Pricing { get; set; }
        public virtual DbSet<Reglements> Reglements { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SeriesTable> SeriesTable { get; set; }
        public virtual DbSet<Taxes> Taxes { get; set; }
        public virtual DbSet<TypePayements> TypePayements { get; set; }
        public virtual DbSet<TypeReglement> TypeReglement { get; set; }
        public virtual DbSet<TypesPieces> TypesPieces { get; set; }
        public virtual DbSet<UserRolesMapping> UserRolesMapping { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<DetailsPiecePrint> DetailsPiecePrint { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Reclamations> Reclamations { get; set; }
        public virtual DbSet<Piece> Piece { get; set; }
        public virtual DbSet<CategorieProduits> CategorieProduits { get; set; }
        public virtual DbSet<DetailsPiece> DetailsPiece { get; set; }
        public virtual DbSet<PricingDetails> PricingDetails { get; set; }
        public virtual DbSet<MaterialReglementDetails> MaterialReglementDetails { get; set; }
        public virtual DbSet<Client> Client { get; set; }
    
        public virtual ObjectResult<GET_BeneficesPerMonth_Result> GET_BeneficesPerMonth(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_BeneficesPerMonth_Result>("GET_BeneficesPerMonth", dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<GET_ENGAGEMENT_FOURNISSEURs_Result> GET_ENGAGEMENT_FOURNISSEURs(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ENGAGEMENT_FOURNISSEURs_Result>("GET_ENGAGEMENT_FOURNISSEURs", dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<GET_ETAT_CLIENTS_Result> GET_ETAT_CLIENTS(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ETAT_CLIENTS_Result>("GET_ETAT_CLIENTS", dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<GET_FournituresPerMonth_Result> GET_FournituresPerMonth(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_FournituresPerMonth_Result>("GET_FournituresPerMonth", dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<GET_MarchandisesPerMonth_Result> GET_MarchandisesPerMonth(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_MarchandisesPerMonth_Result>("GET_MarchandisesPerMonth", dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<GET_RELEVE_COMPTE_Result> GET_RELEVE_COMPTE(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo, Nullable<int> client)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            var clientParameter = client.HasValue ?
                new ObjectParameter("Client", client) :
                new ObjectParameter("Client", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_RELEVE_COMPTE_Result>("GET_RELEVE_COMPTE", dateFromParameter, dateToParameter, clientParameter);
        }
    }
}
